version: "3.9"

networks:
  frankslab-uk:
    external: true

services:
  robot-project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot-project
    ports:
      - "7001:8080"
    restart: unless-stopped
    networks:
      - frankslab-uk
